
name: Publish to NPM

on:
  release:
    types: [prereleased]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/iron'
          registry-url: https://registry.npmjs.org/
          scope: '@wmartzh'
      - run: npm ci
      - run: npm run build
      - name: Authenticate with Npm package registry
        run:
          echo "//registry.npmjs.org:_authToken=${{ secrets.NPM_TOKEN }}" >
          ~/.npmrc
      - run: npm publish --access=public --tag=prerelease
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}



