
name: Publish to NPM

on:
  release:
    types: [released]

jobs:

  publish-iron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access=public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-hydrogen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access=public --tag lts-hydrogen
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-gallium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access=public --tag lts-gallium
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}



